### ISSUE TITLE
Make studio-ar-tools compatible with developer studio 7.5

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cheinig/studio-ar-tools#2]
```
The current version of ar tools is not compatible with the developer studio 7.5 
api. 
This tool plugin should be compatible with all versions of developer studio.


```

Original issue reported on code.google.com by `christop...@gmail.com` on 22 Jul 2011 at 2:56

**Comment by cheinig** [comment]
This problem seems not to be relevant any more, because later versions of the developer studio are backwards compatible. So this enhancement will be closed.
